# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1296076666);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1296076734);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.startup.homepage", "http://localhost:8000/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.13");
user_pref("browser.startup.page", 0);
user_pref("colorzilla.lowercase-hexa", "false");
user_pref("colorzilla.version", "2.2.2");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.6.ubuntu.com:3.6,ubufox@ubuntu.com:0.9rc2,{3e9bb2a7-62ca-4efa-a4e6-f6f6168a652d}:0.8.19,{056d0610-e44d-11df-bccf-0800200c9a66}:3.3.2,{6AC85730-7D0F-4de0-B3FA-21142DD85326}:2.2.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.13");
user_pref("extensions.lastAppVersion", "3.6.13");
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.vidbar.first-time", false);
user_pref("extensions.vidbar.version", "3.3.2");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("ipv6ident.blacklist", "ipv6tools.com|dnsstuff.com|esymbian.info");
user_pref("ipv6ident.newservices", "");
user_pref("ipv6ident.urls", "H|robtex.com - Host|http://www.robtex.com/dns/##.html||4|robtex.com - IP|http://www.robtex.com/ip/##.html||4H|ip2country.cc|http://www.ip2country.cc/?q=##||6|l4x.org|http://dnstools.l4x.org/##||46H|dns.l4x.org|http://dns.l4x.org/##||4|whois.sc|http://www.whois.sc/##||H|whoishostingthis.com|www.whoishostingthis.com/##||H|netcraft|http://uptime.netcraft.com/up/graph/?host=##||H|whois.sc|http://www.whois.sc/domain-explorer/?q=##&sub=Search&filter=y&pool=C&rows=100&bc=25&last=");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1298668247);
